version: '2'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  cassandra2:
    image: cassandra:2.2
    ports:
      - "9042:9042"
    volumes:
      - ${PWD}/docker-files/cassandra.yaml:/etc/cassandra/cassandra.yaml

  dse:
    image: datastax/dse-server
    environment:
      - DS_LICENSE=accept
    ports:
      - "9043:9042"
