version: 2
jobs:
  build:
    working_directory: ~/repo

    environment:
      TERM: dumb
      CASSANDRA_MODE: external
      AKKA_TEST_TIMEFACTOR: 10

    docker:
      - image: bartektomala/scala-sbt:8u181_2.12.6_0.13.17

      - image: scylladb/scylla:2.2.0
        command: --listen-address 0.0.0.0 --broadcast-rpc-address 0.0.0.0 --experimental 1

    steps:
      - checkout

      - restore_cache:
          name: Restoring sbt cache
          keys:
            - sbt

      - run:
          name: Update sbt cache
          command: sbt update

      - save_cache:
          name: Save updated sbt cache
          key: sbt
          paths:
            - "/root/.sbt"
            - "/root/.ivy2"

      - run:
          name: tests
          command: |
            sbt ';set testOptions in Global += Tests.Argument(TestFrameworks.ScalaTest, "-u", "./target/xml-reports/scylladb");test'

      - store_test_results:
          path: ./target/xml-reports

      - store_artifacts:
          path: ./target/test-reports