name: Link Validator

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 5 1 * *'

permissions:
  contents: read

jobs:
  documentation:
    name: ScalaDoc, Documentation with Paradox
    if: github.event.repository.fork == false
    runs-on: Akka-Default
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 25
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.25

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: "Create all API docs and create site with Paradox"
        run: sbt "unidoc; docs/makeSite"

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.5 -- project/link-validator.conf

